[tool.ruff]
exclude = [
    ".git",
    ".github",
    ".idea",
    "venv",
]
line-length = 88
indent-width = 4
target-version = "py310"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[tool.ruff.lint]
select = [
    "F",      # pyflakes
    "E", "W", # pycodestyle
    "YTT",    # flake8-2020
    "B",      # flake8-bugbear
    "Q",      # flake8-quotes
    "T10",    # flake8-debugger
    "PL",     # pylint
    "PIE",    # misc lints
    "PYI",    # flake8-pyi
    "TID",    # tidy imports
    "I",      # isort
    "ISC",    # implicit string concatenation
    "TCH",    # type-checking imports
    "C4",     # comprehensions
    "RUF",    # Ruff-specific rules
    "S102",   # flake8-bandit: exec-builtin
    "NPY002", # numpy-legacy-random
    "G",      # flake8-logging-format
    "D",      # pydocstyle
]
ignore = [
    "PLR2004", # magic-value-comparison: Checks for the use of unnamed numerical constants ("magic") values in comparisons.
    "G004",    # logging-f-string: Checks for uses of f-strings to format logging messages.
    "B904",    # raise-without-from-inside-except: Checks for raise statements in exception handlers that lack a from clause.
    "PLW0603", # global-statement: Checks for the use of global statements to update identifiers.
    "F405",    # undefined-local-with-import-star-usage: Checks for names that might be undefined, but may also be defined in a wildcard import.
    "F403",    # undefined-local-with-import-star: Checks for the use of wildcard imports.
    "E402",    # module-import-not-at-top-of-file: Checks for imports that are not at the top of the file.
    "PYI024",  # collections-named-tuple: Checks for uses of collections.namedtuple in stub files.
    "RUF012",  # mutable-class-default: Checks for mutable default values in class attributes.
    "D104",
    "D100",
]
pylint.max-args = 10
pylint.max-returns = 4

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
lines-between-types = 1

[tool.ruff.lint.pydocstyle]
convention = "google"